# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1d09ca87cbb05d118a7bf7ab35bf564fbe8c2b4a7e9df2dfdb2b40460f4fe464b1d2f43ce57b788b6df3e302903c733bc4c3ddce77e2f9c00e2c1bc1fd20887

test:
  secret_key_base: 6c946364213aaa0938e2966a1bc86b12ec67ed671da5cb50f61bd1c590709468fa959163ec21b375d0b9b1441e4fb8469857b1b0dffd328a2fc01cbe3f95d569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
